### ISSUE TITLE
init and setup

### ISSUE THREAD

**Issue by deolivtiago** [deolivtiago/clarx_api#1]
# description

initialize and setup application

## linked issues

- [x] init phoenix app
- [x] upgrade dependencies
- [x] setup database
- [x] add code analyzer
- [x] add code coverage
- [x] add support libraries
- [x] setup ci
