### ISSUE TITLE
users and accounts

### ISSUE THREAD

**Issue by deolivtiago** [deolivtiago/clarx_api#3]
# description

add users and accounts management

## linked issues

- [x] add migration to create users table
- [x] add schema to validate users attributes
- [x] add context to manage user accounts
- [x] add route and controller to handle users
